name: Deploy Server

on:
  push:
    paths:
      - server/**
      - .github/**
    branches:
      - master

jobs:
  docker:
    name: Docker Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: server
          tags: ahmedsadman/kast-server:latest
  
  # add deploy step
